### ISSUE TITLE
Can I join the project？

### ISSUE THREAD

**Issue by Hodoio** [smalllong/json5-sheet-editor#1]
Is there a possibility of further development for this project?
If possible, I would like to join the open source development of this project. How can I contact you?

**Comment by smalllong** [comment]
Hi Hodoio, sorry I don't check notifications often. Yes it's open source so you can feel free to submit pull requests or create your own fork.

Currently I don't plan to put much time to further develop this project as it now can meet my own requirements. But if you like you can submit your requirements into issues
